ECL-483: Interests On Overdue Payment
hmrc/economic-crime-levy-stubs pull request #35
Opened 2023-10-04 11:45 UTC by nemanjatomanovic

2023-10-04 12:07 UTC, TheDanielDoyle commented on conf/resources/FinancialDataOverdueObligationWithoutInterestDocumentFormed.json
> +{
Can you run a JSON formatter over this.

2023-10-04 12:08 UTC, TheDanielDoyle requested changes
See comment

2023-10-04 13:06 UTC, nemanjatomanovic commented on conf/resources/FinancialDataOverdueObligationWithoutInterestDocumentFormed.json
> +{
Done.

2023-10-05 07:51 UTC, TheDanielDoyle approved these changes

2023-10-05 08:31 UTC, merged